### ISSUE TITLE
夜间模式切换，样式展示有问题

### ISSUE THREAD

**Issue by laijihua** [asjqkkkk/markdown_widget#32]
app 有个夜间模式切换，当切换的时候，一些样式展示出问题

**Comment by asjqkkkk** [comment]
这个问题在提交 90e598a5467b96418e37123e7c03a5243902df00 中已经修复

后序会可以升级到1.2.1来解决这个问题，目前可以暂时通过下面的依赖解决问题

```
  markdown_widget:
    git:
      url: https://github.com/asjqkkkk/markdown_widget.git
      ref: dev
```
